name: 'dbt_alfa'
version: '1.0.0'
config-version: 2

profile: 'dbt_alfa'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

seeds:
  dbt_alfa:
    +schema: GOLD

models:
  dbt_alfa:
    staging:
      +materialized: view
      +schema: SILVER
    marts:
      +materialized: incremental
      +schema: GOLD
